# Generated by Django 4.1.6 on 2023-02-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(max_length=10)),
                ('symbol', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('onehrper', models.CharField(max_length=10)),
                ('twentyfourhrper', models.CharField(max_length=10)),
                ('sevendayper', models.CharField(max_length=10)),
                ('marketcap', models.CharField(max_length=100)),
                ('volume24h', models.CharField(max_length=100)),
                ('volume24h1', models.CharField(max_length=100)),
                ('circulatingsupply', models.CharField(max_length=100)),
            ],
        ),
    ]
