# Generated by Django 4.1.6 on 2023-02-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketfeed',
            name='cid',
        ),
        migrations.AlterField(
            model_name='marketfeed',
            name='id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
